export const DARK_MODE_SET = "DARK_MODE_SET";
export const NORMAL_MODE_SET = "NORMAL_MODE_SET";
export const DEV_MODE_SET = "DEV_MODE_SET";
export const PROD_MODE_SET = "PROD_MODE_SET";
export const TOAST_CLEAR = "TOAST_CLEAR";
export const TOAST_SET_VALUE = "TOAST_SET_VALUE";

export const LOAD_USER_START = "LOAD_USER_START";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const SEND_NOTIFICATION_START = "SEND_NOTIFICATION_START";
export const SEND_NOTIFICATION_SUCCESS = "SEND_NOTIFICATION_SUCCESS";
export const SEND_NOTIFICATION_FAIL = "SEND_NOTIFICATION_FAIL";

export const USER_REGISTRATION_START = "USER_REGISTRATION_START";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

export const USER_DELETE_START = "USER_DELETE_START";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const LOAD_COMMENTS_START = "LOAD_COMMENTS_START";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_FAIL = "LOAD_COMMENTS_FAIL";

export const ALL_COMMENTS_START = "ALL_COMMENTS_START";
export const ALL_COMMENTS_SUCCESS = "ALL_COMMENTS_SUCCESS";
export const ALL_COMMENTS_FAIL = "ALL_COMMENTS_FAIL";

export const REPLY_COMMENTS_START = "REPLY_COMMENTS_START";
export const REPLY_COMMENTS_SUCCESS = "REPLY_COMMENTS_SUCCESS";
export const REPLY_COMMENTS_FAIL = "REPLY_COMMENTS_FAIL";

export const COMMENT_UPDATE_START = "COMMENT_UPDATE_START";
export const COMMENT_UPDATE_SUCCESS = "COMMENT_UPDATE_SUCCESS";
export const COMMENT_UPDATE_FAIL = "COMMENT_UPDATE_FAIL";

export const LOAD_BLOG_POSTS = "LOAD_BLOG_POSTS";
export const UPDATE_POST_LIKES = "UPDATE_POST_LIKES";
export const LOAD_ARCHIVE_POSTS = "LOAD_ARCHIVE_POSTS";


export const SET_LANGUAGE = "SET_LANGUAGE";

export const SET_FAVOURITES = "SET_FAVOURITES";

export const APP_START = "APP_START";
export const BOOT = "BOOT";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const SET_CURRENT_BOOK = "SET_CURRENT_BOOK";
export const SET_CURRENT_CHAPTER = "SET_CURRENT_CHAPTER";
export const SET_CURRENT_CHAPTER_PAGE = "SET_CURRENT_CHAPTER_PAGE";

export const UPDATE_AVATAR = "UPDATE_AVATAR";

export const LOAD_TRACK = "LOAD_TRACK";

export const SET_POST_FROM_NOTIFICATION = "SET_POST_FROM_NOTIFICATION";
export const OPEN_POST_FROM_NOTIFICATION = "OPEN_POST_FROM_NOTIFICATION";
export const CLEAR_POST_FROM_NOTIFICATION = "CLEAR_POST_FROM_NOTIFICATION";

export const SAVE_POST = "SAVE_POST";

export const SET_SESSION = 'SET_SESSION';
export const CLEAR_SESSION = 'CLEAR_SESSION';

// Enhanced Supabase Auth Actions
export const AUTH_LOADING_START = 'AUTH_LOADING_START';
export const AUTH_LOADING_STOP = 'AUTH_LOADING_STOP';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_SET_SESSION = 'AUTH_SET_SESSION';
export const AUTH_SET_USER_PROFILE = 'AUTH_SET_USER_PROFILE';
export const AUTH_SET_ERROR = 'AUTH_SET_ERROR';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';
export const AUTH_SET_INITIAL_LOADING = 'AUTH_SET_INITIAL_LOADING';

// Auth operation actions
export const AUTH_SIGN_UP_START = 'AUTH_SIGN_UP_START';
export const AUTH_SIGN_UP_SUCCESS = 'AUTH_SIGN_UP_SUCCESS';
export const AUTH_SIGN_UP_FAIL = 'AUTH_SIGN_UP_FAIL';
export const AUTH_SIGN_IN_START = 'AUTH_SIGN_IN_START';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAIL = 'AUTH_SIGN_IN_FAIL';
export const AUTH_SIGN_OUT_START = 'AUTH_SIGN_OUT_START';
export const AUTH_SIGN_OUT_SUCCESS = 'AUTH_SIGN_OUT_SUCCESS';
export const AUTH_SIGN_OUT_FAIL = 'AUTH_SIGN_OUT_FAIL';
export const AUTH_PASSWORD_RESET_START = 'AUTH_PASSWORD_RESET_START';
export const AUTH_PASSWORD_RESET_SUCCESS = 'AUTH_PASSWORD_RESET_SUCCESS';
export const AUTH_PASSWORD_RESET_FAIL = 'AUTH_PASSWORD_RESET_FAIL';
export const AUTH_PROFILE_UPDATE_START = 'AUTH_PROFILE_UPDATE_START';
export const AUTH_PROFILE_UPDATE_SUCCESS = 'AUTH_PROFILE_UPDATE_SUCCESS';
export const AUTH_PROFILE_UPDATE_FAIL = 'AUTH_PROFILE_UPDATE_FAIL';
export const AUTH_SESSION_REFRESH_START = 'AUTH_SESSION_REFRESH_START';
export const AUTH_SESSION_REFRESH_SUCCESS = 'AUTH_SESSION_REFRESH_SUCCESS';
export const AUTH_SESSION_REFRESH_FAIL = 'AUTH_SESSION_REFRESH_FAIL';

export const SET_PAGINATION = 'SET_PAGINATION';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const APPEND_POSTS = 'APPEND_POSTS';
export const RESET_POSTS = 'RESET_POSTS';

export const INCREASE_FONT_SIZE = "INCREASE_FONT_SIZE";
export const DECREASE_FONT_SIZE = "DECREASE_FONT_SIZE";

// Azioni per il tema
export const SET_THEME = "SET_THEME";
export const SET_THEME_MODE = "SET_THEME_MODE";
export const SET_BRIGHTNESS = "SET_BRIGHTNESS";
export const SET_FONT_FAMILY = "SET_FONT_FAMILY";
export const SET_SPACING = "SET_SPACING";
export const SET_WIDTH = "SET_WIDTH";
